services:
  web:
    build: .
    ports:
      - 8000:8000
    environment:
      - DB_HOST=pg_db
      - DB_USER=Admin1
      - DB_PASSWORD=Power1983



  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=Power1983
      - POSTGRES_USER=Admin1
    hostname: pg_db