# Generated by Django 5.0.7 on 2024-07-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0002_parcel_update_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='size',
            field=models.IntegerField(),
        ),
    ]
