# Generated by Django 5.0.7 on 2024-07-18 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0003_alter_parcel_size'),
        ('post_machin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='locker',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='post_machin.locker'),
        ),
    ]
