# Generated by Django 5.0.7 on 2024-08-01 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0005_alter_parcel_open_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='order_date_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date published'),
        ),
    ]
